// <auto-generated />
using FonYonetim.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FonYonetim.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230912175327_nasdaqAddMig")]
    partial class nasdaqAddMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FonYonetim.Concrete.Nasdaq", b =>
                {
                    b.Property<int>("NasdaqMarketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("NasdaqMarketPrice")
                        .HasColumnType("float");

                    b.Property<string>("NasdaqMarketSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NasdaqMarketTargetPrice")
                        .HasColumnType("float");

                    b.Property<double>("NasdaqMarketTargetPricePercent")
                        .HasColumnType("float");

                    b.HasKey("NasdaqMarketID");

                    b.ToTable("Nasdaqs");
                });

            modelBuilder.Entity("FonYonetim.Concrete.StockMarket", b =>
                {
                    b.Property<int>("StockMarketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("StockMarketPrice")
                        .HasColumnType("float");

                    b.Property<string>("StockMarketSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StockMarketTargetPrice")
                        .HasColumnType("float");

                    b.Property<double>("StockMarketTargetPricePercent")
                        .HasColumnType("float");

                    b.HasKey("StockMarketID");

                    b.ToTable("StockMarkets");
                });
#pragma warning restore 612, 618
        }
    }
}
