// <auto-generated />
using FonYonetim.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FonYonetim.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230217130334_firstmigration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FonYonetim.Concrete.Portfolio", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<string>("ProductSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductTargetPrice")
                        .HasColumnType("float");

                    b.Property<double>("ProductTargetPricePercent")
                        .HasColumnType("float");

                    b.HasKey("ProductID");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("FonYonetim.Concrete.WatchList", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<string>("ProductSymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductTargetPrice")
                        .HasColumnType("float");

                    b.Property<double>("ProductTargetPricePercent")
                        .HasColumnType("float");

                    b.HasKey("ProductID");

                    b.ToTable("WatchLists");
                });
#pragma warning restore 612, 618
        }
    }
}
